name: download to aliyun oss

on:
  push:
    branches:
      - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'download.list'

jobs:
  download-to-oss:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: copy files to oss
      shell: bash
      env:
        OSS_KEY_ID: ${{ secrets.OSS_KEY_ID }}
        OSS_KEY_SE: ${{ secrets.OSS_KEY_SECRET }}
        OSS_EP: oss-cn-hongkong.aliyuncs.com
        OSS_DL_URL: http://gosspublic.alicdn.com/ossutil/1.6.10/ossutil64
        OSS_DEST: oss://nas-ci/
        URL_FILE: download.list
        OSS_SITE: https://nas-ci.oss-cn-hongkong.aliyuncs.com/
      run: |
        set -ex
        mkdir -p download
        cat $URL_FILE | while read url
        do
          [[ $url =~ ^(http|ftp) ]] && curl -sSL $url -o download/${url##*/}
        done
        mkdir -p ${HOME}/bin
        aliOSS="${HOME}/bin/ossutil"
        curl -o $aliOSS -L $OSS_DL_URL
        chmod a+rx $aliOSS
        $aliOSS config -e $OSS_EP -i $OSS_KEY_ID -k $OSS_KEY_SE
        $aliOSS cp -rf download/ ${OSS_DES}dl/
        rm -f list
        ls download | while read item; do
          echo "${OSS_SITE}/dl/${item}" >> list
        done
        $aliOSS cp -f list ${OSS_DES}list
